### ISSUE TITLE
[Feature]: How do I install?

### ISSUE THREAD

**Issue by jpvelez** [coldenate/citationista#9]
### Feature Title

Installation instructions

### Feature Description

Hi there, I'm looking for a way to integrate Zotero with Remnote and this looks great, but I can't figure out how to install it?

### Use Case

.

### Code of Conduct

- [X] I agree

**Comment by coldenate** [comment]
Hi, just to clarify, this plugin is not yet available on the marketplace. While you cannot install it, you can run the development environment using `npm run dev` if needed. However, I would not recommend doing so at this time.

**Comment by jpvelez** [comment]
Ah, gotcha! Makes sense, thanks for letting me know. For what it's worth, I may not have read the README thoroughly enough, but in any case that wasn't clear to me from the docs. It might be good to spell this out just to avoid other folks being confused =)

In any case, I'm super excited to try this out once it's ready, any idea when that might be?

**Comment by coldenate** [comment]
I'm not entirely sure. I recently had great momentum, but I slowed down to focus on some tasks on the Support side at RemNote. I'm anxious to finish it soon though—it's been a year since I began development.
Yeah, I'll add that to the README!

**Comment by coldenate** [comment]
Do you have Discord? I can add you to the beta test group. (I totally forgot about that option 😭 - you can use the test drive it.)
I just don't have it open to the public, so I'm not overwhelmed with mass bug reports.

**Comment by jpvelez** [comment]
That would be great! My handle is jpv2042

**Comment by coldenate** [comment]
Join the server here, and when I see you I'll add you to the channel :)
https://discord.gg/vEcseqBv

**Comment by coldenate** [comment]
Try this one?

https://discord.gg/AV2SEDvh

**Comment by jpvelez** [comment]
*in hacker voice*

_i'm in_
